name: unit-test

on:
  push:
    branches: main

jobs:
  deno:
    name: typescript
    runs-on: linux
    defaults:
      run:
        working-directory: esm
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31
        with:
          deno-version: v1.x

      - name: lint
        run: deno lint

      - name: test
        run: deno test

