name: unit-test

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "**/src/**"

jobs:
  deno:
    name: typescript
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: esm
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: lint
        run: deno lint

      - name: test
        run: deno test

  c:
    name: c c++
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: c
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: cmake -S ./ -B build

      - run: cmake --build build

      - name: Run unit tests
        run: cd build && ctest

  rust:
    name: rust
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v4

      - run: cargo test

  haskell:
    name: haskell
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: haskell
    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.10.1"
          enable-stack: true
          stack-version: "latest"

      - run: stack test
