name: unit-test

on:
  push:
    branches: main

jobs:
  deno:
    name: typescript
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: esm
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31
        with:
          deno-version: v1.x

      - name: lint
        run: deno lint

      - name: test
        run: deno test

  c:
    name: c c++
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: c
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: threeal/cmake-action@v1.3.0
        with:
          source-dir: c

      - name: build
        run: cmake -S ./ -B build 

      - name: compile and test
        run: cd build && make && ./src/tdd

  rust:
    name: rust
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1

      - uses: actions-rs/cargo@v1
        with:
          command: test
